apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
          - name: myapp-container
            image: my-app-image
          restartPolicy: Never
