apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-data
spec:
  storageClassName: google-storage # no need to create PV as it's created automatically
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteOnce
