apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-network-policy
  namespace: prod
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: prod
      podSelector:
        matchLabels:
          role: backend
    ports:
      - protocol: TCP
        port: 6379
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.1.1/32
    ports:
    - protocol: TCP
      port: 80
