---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp-container
      image: my-app-image
      ports:
        - containerPort: 8081
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
      env:
        - name: APP_PROP
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PROP1
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASS
      volumeMounts:
        - mountPath: /usr/src/app/images
          name: images-volume
  volumes:
    - name: images-volume
      emptyDir:
        sizeLimit: 100Mi
