---
apiVersion: v1
kind: Service
metadata:
  name: external-service
  labels:
    name: external-service
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8080
    nodePort: 30080
  selector:
    name: myapp
---
apiVersion: v1
kind: Service
metadata:
  name: internal-service
  labels:
    name: internal-service
spec:
  type: ClusterIP
  ports:
  - port: 8081
  selector:
    name: myapp
