#!/usr/bin/env bash

# Exit if the commit is a merge
if [[ "$2" = "merge" ]]
then
  exit 0
fi

current_branch_name=$(git rev-parse --abbrev-ref HEAD)
current_task_id=$(echo $current_branch_name | awk -F'/' '{print $2}')

# Exit if task ID not found
if [[ -z $current_task_id ]]
then
  echo Task ID not found
  exit 0
fi

# Exit if the task ID have been added already
if [[ $(cat $1) == $current_task_id* ]] 
then
  echo Task ID already added
  exit 0
fi

# Exit if Tempo commit
if grep -q Tempo $1 ; then
  echo Tempo commit
  exit 0
fi

# Add current task ID to a commit message if the current branch has a preffix
if [[ $current_branch_name == preffix* ]] 
then
  echo Prepend message with task ID
  sed -i 1s/^/"${current_task_id}"/ $1
fi
