# Run command: ./ngrok --config /ngrok-config.yml --all

authtoken: <token>
region: eu
tunnels:
  web:
    proto: http
    addr: 8000
    host_header: localhost:8000

  api:
    proto: http
    addr: 8080
    host_header: localhost:8080


